language: java

jdk:
- oraclejdk8

before_install:
- RUN mkdir -p /tmp/kindlegen && \
  cd /tmp/kindlegen && \
  curl http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz -o kindlegen.tar.gz && \
  tar xvf kindlegen.tar.gz && \
  chown root. kindlegen && \
  chmod 755 kindlegen && \
  mv kindlegen /usr/local/bin/ && \
  rm -rf /tmp/kindlegen
- chmod +x gradlew
- chmod +x gradle/wrapper/gradle-wrapper.jar

script:
- ./gradlew test --stacktrace