language: java

jdk:
- oraclejdk8

before_install:
- curl http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz -o /tmp/kindlegen.tar.gz
- tar xvf /tmp/kindlegen.tar.gz
- chmod +x kindlegen
- export PATH=$PATH:.
- chmod +x gradlew
- chmod +x gradle/wrapper/gradle-wrapper.jar

script:
- ./gradlew test --stacktrace
- ./gradlew jacocoTestReport

after_success:
- bash <(curl -s https://codecov.io/bash)